CREATE TABLE order_item
(
    id       BIGINT  generated by default as identity ,
    order_id BIGINT,
    book_id  BIGINT,
    quantity INT,
    FOREIGN KEY (order_id) REFERENCES order_books (id),
    FOREIGN KEY (book_id) REFERENCES books (id)
);
