INSERT into books(title, author, price, description, cover_image_url, rating, quantity, created_at, updated_at)
values ('Tale of two cities', 'Charles Dickens', '350',
        'The novel tells the story of the French Doctor Manette, his 18-year-long imprisonment in the Bastille in Paris, and his release to live in London with his daughter Lucie whom he had never met. The story is set against the conditions that led up to the French Revolution and the Reign of Terror.',
        '1586_f1601742134.png', 5, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Little women', 'Louisa May Alcott', '450',
        'It is set during and after the Civil War and tells the story of the March family, principally the four girls: Meg, Jo, Beth, and Amy. The girls struggle and grow as a family while their father is serving in the war and learn the value of hard work, self-sacrifice, and love.',
        '1586_f1601742134.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('How to stop worrying and start living', 'Dale Carnegie', '550',
        'The book consists of some True Stories which will help the readers in conquering worry to lead you to success in life. The book is full of similar incidences and narrations which will make our readers to understand the situation in an easy way and lead a happy life.',
        '1586_f1601742134.png', 4.5, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Atomic Habits', 'James Clear', '300',
        'Using a framework called the Four Laws of Behavior Change, Atomic Habits teaches readers a simple set of rules for creating good habits and breaking bad ones.',
        '1586_f1601742134.png', 3.6, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Desert Leopards', 'Nikki Grace', '250',
        'As the age unfolds in a dark and treacherous enactment of religious inspired violence throughout the world, an avatar rises in the mountains and meets his destiny in the desert sands. Michael of the morning, chosen of God, is born the child of simple ranchers in the primitive Rocky mountains of Northwest America',
        '839_f1600090867.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('The Prince of Patliputra', 'Shreyas Bhave', '87',
        '272 Bc Bharathvarsha, Laiid Of The Aryas Samrat Bindusar, son of Chandragupta and the second Samrat Chakravartin of all the Aryas rules over the massive subcontinent from his holy seat in Patliputra.',
        '1066_f1601736038.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Return of The Trojan Horse', 'Amit Dubey', '17',
        'Return Of The Trojan is the riveting narration of how he is compelled to draw inputs from his personal life, and use sharp thinking and advanced technology to solve the criminal cases he is brought into.',
        '828_f1600083036.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('A Million Cars For A Billion People', 'Gautam Sen', '20',
        'The very first cars that came to India; the early beginnings of the industry; the nascent history of the automobile across nations like Germany, France, US, the UK, Italy, Japan and South Korea, is narrated with authority and charm, from the viewpoint of the quest for the ultimate people’s car',
        '1066_f1601736038.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Prisoner of Yakutsk', 'Shreyas Bhave', '21',
        'What exactly happened to Netaji Subhash Chandra Bose?• In 1945, Netaji Subhash Chandra Bose, Leader of the INA leaves Singapore to take a series of flights, and dies in Taiwan after his plane crashes near Formosa. Or so it seems.',
        '1311_f1601737652.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('I''m So Hacked', 'Gautam Mayekar', '200',
        '@v! is a hacker who spends his days working in India’s number one anti-virus company as a security researcher and his nights, crawling through underground hacking forums',
        '834_f1600085811.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('The other Guy', 'Aakash Mehrotra', '200',
        'Set in contemporary India, The Other Guy is a tale of forbidden love. Amidst laws which declare them criminals,emotional repression and societal suppression, Nikhil and Anuj are two talented young men, deeply in love with eachother',
        '1585_f1601742130.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('What The Fuq?', 'Dr. Minnu Bhonsle', '200',
        'Even today, social taboos prevent us from discussing sex openly, often leading to psycho-social and even medical conditions.',
        '924_f1600157336.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('300 brave Men', 'Gautam Pradhan', '200',
        'Land of the Marathas, Western India, 1641-1660 The Indian sub - continent is ruled by three tyrannical Sultanates... the powerful Mughals in the North, and the Shia rulers - Adilshah and Qutubshah in the South',
        '1579_f1601742045.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Asura', 'Anand Neelakantan', '200',
        'The epic tale of victory and defeatƒ The story of the Ramayana had been told innumerable times. The enthralling story of Rama, the incarnation of God, who slew Ravana, the evil demon of darkness, is known to every Indian',
        '1358_f1601737869.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Venus with a P*nis', 'Almas Hussain', '200',
        'Meet Rajan, the irresponsible younger son in a family of doctors. He’s reckless. He’s rebellious. And he’s dressing up like a woman these days. No. He’s not a cross-dresser. Nor is he transgender',
        '1325_f1601737715.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Bhoot, Bhavish, Bartaman', 'Mehool Parekh', '200',
        'A beautiful woman is found brutally murdered in her bed. The usual suspects are arrested by the Police until an odd-ball amateur sleuth starts to investigate. Something about the murder does not sit right with him',
        '1080_f1601736098.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Healing The Blue Planet', 'Bane Singh', '200',
        'What ails Mother Earth? The answer can be found in the propensities of Man, her most gifted, but alas, also her most prodigal son. The world today may look to be the oyster to modern Man, with his faculties of creativity, inventiveness and enterprise',
        '1627_f1601742341.png', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);




